### ISSUE TITLE
Back-up Service: Automations are enabled by default

### ISSUE THREAD

**Issue by Fingerling42** [airalab/homeassistant-robonomics-integration#19]
**Проблема:**
После восстановления из бэкапа выключенные автоматизации не сохраняются, и включаются по умолчанию. Это не очень хорошо, так как возможно триггернуть автоматизации, которые не хотелось бы триггерить (например, по пожарной безопасности).

**Предложение:**
Найти способ, как по умолчанию после восстановления из бэкапа держать автоматизации выключенными.

**Comment by LoSk-p** [comment]
В версии 1.5.3 добавлен полный бэкап, который будет сохранять в том числе статус автоматизаций
