### ISSUE TITLE
How to find controller address after inital integration setup 

### ISSUE THREAD

**Issue by ensrationis** [airalab/homeassistant-robonomics-integration#33]
No info about controller addr, and where I can change it?
![image](https://github.com/airalab/homeassistant-robonomics-integration/assets/14291169/663a98a7-ffd4-47ad-9e06-74d6b779f9e2)

**Comment by LoSk-p** [comment]
To change controller or owner address you should reinstall Robonomics integration.

Current configuration with controller credentials and owner address can be found in `<homeassistant_config>/.storage/core.config_entries` file, where <homeassistant_config> is the path to your Home Assistant configuration directory.
